Eq5 144 gs rapport pas evaluer
Ishnewalon/eq5_projet pull request #43
Opened 2021-11-18 23:55 UTC by FrostDistrict

2021-11-18 23:59 UTC, OussaKab commented on backend/src/main/java/com/gestionnaire_de_stage/service/ContractService.java
> +        Assert.notNull(contract, "Le contract ne peut pas être null");
je savais pas que ça existait, t'as dead

2021-11-19 00:06 UTC, OussaKab requested changes

2021-11-19 00:06 UTC, OussaKab commented on backend/src/main/java/com/gestionnaire_de_stage/controller/StudentController.java
> +                    });
utilise le fonctional programming avec map à la place dans un service

2021-11-19 00:06 UTC, OussaKab commented on backend/src/test/java/com/gestionnaire_de_stage/controller/StudentControllerTest.java
> +        Stage stage3 = getDummyStage();stage3.setId(3L);
```suggestion
        Stage stage2 = getDummyStage();
        stage2.setId(2L);
        
        Stage stage3 = getDummyStage();
        stage3.setId(3L);
```

2021-11-19 00:06 UTC, OussaKab commented on backend/src/test/java/com/gestionnaire_de_stage/controller/StudentControllerTest.java
> +        return new ArrayList<>(Arrays.asList(stage1, stage2, stage3));
```suggestion
        return List.of(stage1, stage2, stage3);
```

2021-11-19 00:06 UTC, OussaKab commented on backend/src/test/java/com/gestionnaire_de_stage/service/ContractServiceTest.java
> +        assertThat(actual.getOffer()).isEqualTo(studentMonitorOfferDTO.getOffer());
```suggestion
        assertThat(actual).isEqualTo(studentMonitorOfferDTO);

2021-11-19 00:06 UTC, OussaKab commented on backend/src/test/java/com/gestionnaire_de_stage/service/StageServiceTest.java
> +        return new ArrayList<>(Arrays.asList(stage1, stage2, stage3));
```suggestion
        Stage stage2 = getDummyStage();
        stage2.setId(2L);
        
        Stage stage3 = getDummyStage();
        stage3.setId(3L);
        
        return List.of(stage1, stage2, stage3);
```

2021-11-19 00:06 UTC, OussaKab commented on gestionnaire_de_stage_frontend/src/components/ManagerView/RapportsView/Rapport/StudentsNotYetEvaluated/StudentsNotYetEvaluated.jsx
> +                    <th>Supervisor</th>
```suggestion
                    <th>Superviseur</th>
```

2021-11-19 01:36 UTC, FrostDistrict commented on backend/src/test/java/com/gestionnaire_de_stage/service/ContractServiceTest.java
> +        assertThat(actual.getOffer()).isEqualTo(studentMonitorOfferDTO.getOffer());
no bueno

2021-11-19 01:44 UTC, OussaKab approved these changes

2021-11-19 01:49 UTC, merged