Forgot password
Ishnewalon/eq5_projet pull request #59
Opened 2021-11-21 07:09 UTC by BertSa

Closing #56 
WIP Mais cela donne une idée de ce que ça aura l'aire.
Aussi je rajouterais le send email par après.

2021-11-21 23:55 UTC, OussaKab requested changes

2021-11-21 23:55 UTC, OussaKab commented on backend/src/main/java/com/gestionnaire_de_stage/exception/EmailDoesNotExistException.java
> +
```suggestion

public class EmailDoesNotExistException extends Exception {
    public EmailDoesNotExistException(String message) {
        super(message);
    }
    public EmailDoesNotExistException() {
        super("L'email n'existe pas");
    }
    

```

On set jamais un message avec un setter dans une exception, on fais juste instancié une nouvelle exception.
Et le message dois être envoyer normalement lors de l'instanciation.
T'as aussi pas besoin de `@Getter` puisque la classe parent te donne accès au message à travers `getMessage()`

2021-11-21 23:55 UTC, OussaKab commented on backend/src/main/java/com/gestionnaire_de_stage/exception/UnusableTokenException.java
> +    }
```suggestion
public class UnusableTokenException extends Exception {

    public UnusableTokenException(String message) {
     super(message);
    }
```
Voir review précédant

2021-11-21 23:55 UTC, OussaKab commented on backend/src/main/java/com/gestionnaire_de_stage/controller/PasswordResetController.java
> +    }
Est-ce que c'est possible de faire une logique qui regroupe les trois méthodes en une seule avec un switch case?

2021-11-21 23:55 UTC, OussaKab commented on backend/src/main/java/com/gestionnaire_de_stage/exception/DoesNotExistException.java
> +}
```suggestion

public class DoesNotExistException extends Exception {

    public DoesNotExistException(String message) {
          super(message);
    }
}
```

2021-11-21 23:55 UTC, OussaKab commented on backend/src/main/java/com/gestionnaire_de_stage/model/PasswordResetToken.java
> +    private boolean unusable;//TODO maybe un puller?
```suggestion
    private boolean unusable
```
pas de puller, au moment du call on checkera si la date a dépassé l'interval de temps alloué . Si ça dépasse, on dit à l'utilisateur que le token a expiré et il doit refaire sa demande, sinon on le laise update son mdp

2021-11-21 23:55 UTC, OussaKab commented on backend/src/main/java/com/gestionnaire_de_stage/service/StudentService.java
> +        if (isEmailInvalid(email)) throw new EmailDoesNotExistException();
```suggestion
        if (isEmailInvalid(email)) 
            throw new EmailDoesNotExistException();
```
C'est seulement dans les langages familier ou le one line if est correct.
Dans java, c'est toujours en plusieurs lignes.

2021-11-21 23:55 UTC, OussaKab commented on backend/src/test/java/com/gestionnaire_de_stage/service/PasswordResetServiceTest.java
> +    private StudentService studentService;
```suggestion
    @Mock
    private SupervisorService supervisorService;
    
    @Mock
    private StudentService studentService;
```
pour le aesthetic

2021-11-22 05:01 UTC, OussaKab requested changes

2021-11-22 05:01 UTC, OussaKab commented on backend/src/main/java/com/gestionnaire_de_stage/service/SupervisorService.java
> +        if (isIdNotValid(supervisor.getId())) throw new IdDoesNotExistException();
```suggestion
        if (isIdNotValid(supervisor.getId())) 
            throw new IdDoesNotExistException();
```

2021-11-22 18:50 UTC, BertSa commented on backend/src/main/java/com/gestionnaire_de_stage/model/PasswordResetToken.java
> +    private boolean unusable;//TODO maybe un puller?
C'est pour ca que c'est un todo

2021-11-22 22:02 UTC, OussaKab requested changes

2021-11-22 22:02 UTC, OussaKab commented on backend/src/test/java/com/gestionnaire_de_stage/service/StudentServiceTest.java
> +        //noinspection ConstantConditions
met juste @SuppressWarning("ConstantConditions") au-dessus de la classe, c'est mieux que des commentaire d'intellij

2021-11-22 22:02 UTC, OussaKab commented on gestionnaire_de_stage_frontend/src/services/user-service.js
> +                return false;
```suggestion
                if (response.status === 200) {
                    toast.fire({title: body.message};
                }
                if (response.status === 400) {
                    toastErr.fire({title: body.message})
                }
                return response.ok;
```

2021-11-22 22:02 UTC, OussaKab commented on gestionnaire_de_stage_frontend/src/services/user-service.js
> +                return false;
```suggestion
            return response.json().then((body) => {
                if (response.status === 200) {
                    toast.fire({title: body.message});
                }
                if (response.status === 400) {
                    toastErr.fire({title: body.message});
                }
                return response.ok;
```

2021-11-23 01:05 UTC, BertSa commented on gestionnaire_de_stage_frontend/src/services/user-service.js
> +                return false;
.

2021-11-23 01:06 UTC, BertSa commented on gestionnaire_de_stage_frontend/src/services/user-service.js
> +                return false;
k

2021-11-23 01:15 UTC, OussaKab approved these changes
Gros chackal!

2021-11-23 01:15 UTC, merged