Better register
Ishnewalon/eq5_projet pull request #66
Opened 2021-11-24 07:56 UTC by BertSa

2021-11-24 20:10 UTC, ImemBA1 requested changes

2021-11-24 20:10 UTC, ImemBA1 commented on gestionnaire_de_stage_frontend/src/components/SharedComponents/BtnBack.jsx
> +                   onClick={() => history.length > 0 ? history.goBack() : null}>Retour</button>
a teste et peut etre push vers login

2021-11-24 20:14 UTC, ImemBA1 commented
https://media.discordapp.net/attachments/483348725704556557/834754102575235142/image0.gif

2021-11-25 02:38 UTC, ImemBA1 approved these changes

2021-11-25 04:14 UTC, OussaKab commented on gestionnaire_de_stage_frontend/src/components/Unauthenticated/Register/RegisterMonitor.jsx
> +        // noinspection JSUnresolvedVariable
Est-ce que c'est nécessaire?

2021-11-25 05:16 UTC, OussaKab requested changes

2021-11-25 05:16 UTC, ImemBA1 commented on gestionnaire_de_stage_frontend/src/services/use-auth.js
> +        localStorage.removeItem("type");
c fait

2021-11-25 05:31 UTC, ImemBA1 approved these changes

2021-11-25 05:31 UTC, merged