Optimise forms
Ishnewalon/eq5_projet pull request #73
Opened 2021-11-27 00:05 UTC by ImemBA1

2021-11-29 15:51 UTC, OussaKab requested changes

2021-11-29 15:51 UTC, OussaKab commented on gestionnaire_de_stage_frontend/src/services/user-service.js
> +    return await fetch(`${urlBackend}/${typeUser}/change_password/${id}`, requestInit(methods.POST, password)).then(response => {
```suggestion
    return await fetch(`${urlBackend}/${typeUser}/change_password/${id}`, requestInit(methods.PUT, password)).then(response => {
```

2021-11-29 16:42 UTC, ImemBA1 commented on backend/src/main/java/com/gestionnaire_de_stage/service/OfferApplicationService.java
> +    }
non

2021-11-29 16:45 UTC, ImemBA1 commented on gestionnaire_de_stage_frontend/src/components/Offers/OfferView.jsx
> +                            a {Math.ceil((new Date().getTime() - new Date(offer.created).getTime()) / (1000 * 3600 * 24))} jour(s)
qwpe[jhugqhhehgeibpoijhgrpoikljp;oirhg[rnwsth
]

2021-11-30 01:43 UTC, FrostDistrict approved these changes
so many lines jeeeeezz

2021-11-30 02:05 UTC, BertSa approved these changes

2021-11-30 02:07 UTC, BertSa approved these changes

2021-11-30 02:09 UTC, merged